
version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "$API_PORT:$API_PORT"
    environment: 
      - STREAM_ADRESS=
      - ENVIRONMENT=PROD
      - API_PORT=8080
    restart: "always"
